name: Run SODA
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€ minute (0 - 59)
    #        â”‚  â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€ hour (0 - 23)
    #        â”‚  â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the month (1 - 31)
    #        â”‚  â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€ month (1 - 12 or JAN-DEC)
    #        â”‚  â”‚ â”‚ â”‚ â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€ day of the week (0 - 6 or SUN-SAT)
    - cron: "0 8 * * 1" # Every Monday at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache heliopy data
      uses: actions/cache@v2
      with:
        path: ~/heliopy/data/spice
        # Bump this version number ot clear the heliopy spice cache
        key: 'v1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements.txt
    - name: Generate HTML
      run: |
        python run_soda.py
    - name: Deploy ðŸš€
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: pages
        folder: . # The folder the action should deploy.
